name: PR Build

on:
  pull_request:
    branches:
    - main

jobs:
  build:
    name: PR build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.8.0
      with:
        dotnet-version: 7.0.x

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    # Run the tests, ideally should stop here if a fail and also publish results as artifacts
    - name: Test
      run: dotnet test --no-restore
